services:
  searxng:
    build:
      context: .
      dockerfile: searxng.dockerfile
    expose:
      - 8080
    ports:
      - 8001:8080
    networks:
      - future-search

  search-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    expose:
      - 3003
    ports:
      - 3003:3003
    networks:
      - future-search
  

  # search-frontend:
  #   build:
  #     context: .
  #     dockerfile: app.dockerfile
  #     args:
  #       - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3003
  #       - NEXT_PUBLIC_API_URL=http://127.0.0.1:3003/api
  #   depends_on:
  #     - search-backend
  #   expose:
  #     - 3000
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - future-search

      
networks:
  future-search: